name: chain_wallet
description: Chain wallet client library
version: 0.1.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: 3.10.0

dependencies:
  bip39: ^1.0.6
  convert: ^3.1.1
  cryptography: ^2.5.0
  dart_bip32_bip44: ^0.2.0
  dio: ^5.3.0
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.0.0
  http: ^1.1.0
  http_parser: ^4.0.2
  path_provider: ^2.0.15
  web3dart: ^2.7.0
  web_socket_channel: ^2.4.0

dev_dependencies:
  build_runner:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0+1
  web3dart_builders: ^0.0.7
