name: chain_wallet
description: Chain wallet client library
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.7

dependencies:
  bip39: ^1.0.6
  convert: ^3.1.1
  cryptography: ^2.0.5
  dart_bip32_bip44: ^0.2.0
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_secure_storage: ^4.2.1
  http: ^0.13.5
  http_parser: ^4.0.2
  path_provider: ^2.0.11
  web3dart: ^2.5.1
  web_socket_channel: ^2.2.0

dev_dependencies:
  build_runner:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0
  web3dart_builders: ^0.0.2
